# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\"\x1b\n\x0b\x65\x63hoRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"!\n\x0c\x65\x63hoResponse\x12\x11\n\techo_text\x18\x01 \x01(\t26\n\x06\x65\x63hoer\x12,\n\x07SayEcho\x12\x0c.echoRequest\x1a\r.echoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=14
  _globals['_ECHOREQUEST']._serialized_end=41
  _globals['_ECHORESPONSE']._serialized_start=43
  _globals['_ECHORESPONSE']._serialized_end=76
  _globals['_ECHOER']._serialized_start=78
  _globals['_ECHOER']._serialized_end=132
# @@protoc_insertion_point(module_scope)
